{{if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1"}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptopussecretcontroller
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "vault.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{end}}
