/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	cryptopussecretcontrollerv1alpha1 "puzzle.ch/cryptopussecretcontroller/pkg/apis/cryptopussecretcontroller/v1alpha1"
	versioned "puzzle.ch/cryptopussecretcontroller/pkg/client/clientset/versioned"
	internalinterfaces "puzzle.ch/cryptopussecretcontroller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "puzzle.ch/cryptopussecretcontroller/pkg/client/listers/cryptopussecretcontroller/v1alpha1"
)

// SecretClaimInformer provides access to a shared informer and lister for
// SecretClaims.
type SecretClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SecretClaimLister
}

type secretClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretClaimInformer constructs a new informer for SecretClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretClaimInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretClaimInformer constructs a new informer for SecretClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CryptopussecretcontrollerV1alpha1().SecretClaims(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CryptopussecretcontrollerV1alpha1().SecretClaims(namespace).Watch(options)
			},
		},
		&cryptopussecretcontrollerv1alpha1.SecretClaim{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretClaimInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretClaimInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cryptopussecretcontrollerv1alpha1.SecretClaim{}, f.defaultInformer)
}

func (f *secretClaimInformer) Lister() v1alpha1.SecretClaimLister {
	return v1alpha1.NewSecretClaimLister(f.Informer().GetIndexer())
}
